### ISSUE TITLE
Fichiers de configuration

### ISSUE THREAD

**Issue by Stan92** [alexylem/jarvis#190]
Bonjour,
Ce n'est pas une issue mais une demande éventuelle de fonctionnalités.
Est il possible ou serait il envisageable de prévoir les points suivants :
- Permettre de créer un fichier de configuration & de commandes par Utilisateur ?
- Pourvoir exécuter Jarvis en précisant le fichier de configuration & de commandes (en gros, le profil utilisateur)

Le but de fichier de configuration serait uniquement de permettre de récupérer le nom et le magic word 
Tous les autres paramètres de config seraient communs (Moteur de synthèse, de reconnaissance, etc...)

**Comment by alexylem** [comment]
Ok si je comprends bien tu voudrais qu'une instance de Jarvis puisse gérer plusieurs pofils d'utilisateurs pour les différentes personnes de la maison?

On pourrait aussi imaginer que ca soit automatique pas au démarrage, mais au déclenchement du hotword (ex: 1 hotword par utilisateur):
```yml
Alex: Jarvis?
Jarvis: Oui Alex?
Alex: Check mes mails
Jarvis: tu as 2 emails non lus
[...]
Sarah: Siri?
Siri: Oui Sarah?
Sarah: Check mes mails
Siri: Tu n'as aucun email non lu
```
