### ISSUE TITLE
Catégoriser l'affichage des commandes possible

### ISSUE THREAD

**Issue by Gilles76** [alexylem/jarvis#208]
Au fur et à mesure Jarvis va pouvoir gérer beaucoup de chose dans pas mal de domainess.

La liste des commandes en fonction des plugins et autres va s'accroitre.

Je voudrai lancer une discussion sur la possibilité d'implanter un système de catégorie/tri.

Pourquoi ne pas reprendre les catégories et non des plugins.
exemple: catégorie => tous, affiche tout.
catégorie => media  affiche kodi, livebox etc....

mais on pourrai choisir catégorie => media => tout. 

cela afficherai tout ce qui est disponible dans media.

Qu'en pensez-vous ?

**Comment by alexylem** [comment]
Ok très bonne idée, j'imagine que tu parles pour l'affichage des commandes au lancement de Jarvis?
![image](https://cloud.githubusercontent.com/assets/11017174/20030085/d9911ee2-a35d-11e6-95d7-f6d1922fd044.png)
D'ailleurs je vois qu'il y a aussi les commandes imbriquées qui s'affichent, je devrais les afficher au moment ou l'ordre en question est reçu...
Donc voici ce que je propose:
```yml
Jarvis: Bonjour Alex
# your commands:
#	ANNULE*|TERMINE*	*MERCI*	*AIDE*
#	*COMMENT*APPELLE*	*BONJOUR*|*SALUT*	*AU REVOIR*|*BYE*
#	*TEST*			*VERSION*		*REPETE (*) ET (*)
#	*SENS*VIE*		*CA VA*
# jarvis-gmail:
#	*MAIL*
# jarvis-home-control:
#	*ETEIN*	*ALLUME*
# jarvis-time:
#	*QUELLE HEURE*		*QUEL JOUR*
# jarvis-weather-wunderground:
#	*METEO*DEMAIN*		*METEO*
Alex: Ca va?
Jarvis: Très bien et toi?
# *OUI*	*NON*
Alex:
```
