### ISSUE TITLE
ligne 622 : printf: « % » : caractère de format manquant

### ISSUE THREAD

**Issue by azertigrou** [alexylem/jarvis#247]
Bonjour,

Un petit problème sur les %. 
Voici ma commande:
```shell
*LUMIERE*BUREAU*A (*) POURCENT*==~pi/jarvis/hooks/filtre_lumiere.sh (1); say "Lumière du bureau à (1) pourcents";
```
Et le résultat:
```yml
Thierry: ./jarvis.sh: ligne 622 : printf: « % » : caractère de format manquant
lumière du bureau à 50
Lidia: Je ne comprends pas: lumière du bureau à 50 %
```
