### ISSUE TITLE
Discussion multiple avec jarvis ?

### ISSUE THREAD

**Issue by lbdii** [alexylem/jarvis#358]
Bonjour, alors voila mon problème, j'aimerai que Jarvis puisse répondre à ma place à mes clients car je tiens une boutique informatique mais on est bloqué au bout d'un moment avec les réponses .
```shell
 *ORDINATEUR PORTABLE*==say "Daccord, quel est votre probleme ?"
 >*INTERNET*==say "tres bien"
 >>*OUI*==say "daccord"
 >>>*OUI*==say "ok"
 >>>*NON*==say "ok"
 >>*NON*==say "daccord"
 >>>*OUI*==say "ok"
 >>>*OUI*==say "ok"
 ```
Resultat : 
```yml
lbcdi : ordinateur portable
jarvis : daccord quel est votre probleme ?
lbcdi : internet ne fonctionne pas
jarvis : tres bien
lbcdi : non
jarvis : je ne comprend pas : non
```
Donc j'aimerai savoir si il y a moyen que jarvis puisse nous répondre avec des choix multiples. même via des variables. Merci
